terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 1:  1689 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 2:  1691 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 3:  1693 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 4:  1695 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 5:  1697 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 6:  1699 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 7:  1701 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 8:  1703 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 9:  1705 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 10:  1707 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 11:  1709 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 12:  1711 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 13:  1713 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 14:  1715 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 15:  1717 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 16:  1719 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 17:  1721 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 18:  1723 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 19:  1725 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 20:  1727 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 21:  1729 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 22:  1731 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 23:  1733 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 24:  1735 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 25:  1737 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 26:  1739 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 27:  1741 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 28:  1743 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 29:  1745 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 30:  1747 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 31:  1749 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 32:  1751 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 33:  1753 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 34:  1755 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 35:  1759 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 36:  1761 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 37:  1763 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 38:  1765 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 39:  1767 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 40:  1769 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 41:  1771 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 42:  1773 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 43:  1775 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 44:  1777 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 45:  1779 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 46:  1781 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 47:  1783 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 48:  1785 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 49:  1787 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 50:  1791 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 51:  1793 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 52:  1799 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 53:  1801 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 54:  1803 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 55:  1805 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 56:  1807 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 57:  1809 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 58:  1811 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 59:  1813 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 60:  1815 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 61:  1817 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 62:  1819 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 63:  1821 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 64:  1823 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 65:  1825 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 66:  1827 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 67:  1829 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 68:  1831 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 69:  1833 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 70:  1835 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 71:  1837 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 72:  1839 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 73:  1841 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 74:  1843 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 75:  1845 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 76:  1847 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 77:  1849 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 78:  1851 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 79:  1853 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 80:  1855 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 81:  1857 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 82:  1859 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 83:  1861 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 84:  1863 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 85:  1865 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 86:  1867 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 87:  1869 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 88:  1871 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 89:  1873 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 90:  1877 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 91:  1879 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 92:  1881 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 93:  1883 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 94:  1885 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 95:  1888 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/14.pos.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-4-0-a-val.sh: line 96:  1890 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-a.pddl $1
