terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 1:  9425 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 2:  9427 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 3:  9429 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 4:  9431 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 5:  9433 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 6:  9435 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 7:  9437 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 8:  9439 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 9:  9441 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 10:  9443 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 11:  9445 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 12:  9447 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 13:  9449 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 14:  9451 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 15:  9453 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 16:  9455 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 17:  9457 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 18:  9459 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 19:  9461 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 20:  9463 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 21:  9465 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 22:  9467 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 23:  9469 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 24:  9471 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 25:  9473 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 26:  9475 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 27:  9477 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 28:  9479 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 29:  9481 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 30:  9483 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 31:  9485 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 32:  9487 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 33:  9489 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 34:  9491 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 35:  9493 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 36:  9495 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 37:  9497 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 38:  9499 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 39:  9501 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 40:  9503 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 41:  9505 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 42:  9507 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 43:  9509 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 44:  9511 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 45:  9513 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 46:  9515 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 47:  9517 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 48:  9519 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 49:  9521 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 50:  9523 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 51:  9525 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 52:  9527 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 53:  9529 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 54:  9531 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 55:  9533 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 56:  9535 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 57:  9537 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 58:  9539 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 59:  9541 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 60:  9543 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 61:  9545 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 62:  9547 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 63:  9549 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 64:  9551 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 65:  9553 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 66:  9555 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 67:  9557 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 68:  9559 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 69:  9561 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 70:  9563 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 71:  9565 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 72:  9567 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 73:  9569 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 74:  9571 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 75:  9573 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 76:  9575 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 77:  9577 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 78:  9579 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 79:  9581 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 80:  9583 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 81:  9585 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 82:  9587 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 83:  9589 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 84:  9591 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 85:  9593 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 86:  9595 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 87:  9597 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 88:  9599 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 89:  9601 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 90:  9603 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 91:  9605 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 92:  9607 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 93:  9609 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 94:  9611 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/19.neg.program'
./scripts/neg/ijcai19/gb-val/gb-NEG-1-4-a-val.sh: line 95:  9613 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-a.pddl $1
