terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 1:  6116 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 2:  6118 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 3:  6120 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 4:  6122 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 5:  6124 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 6:  6126 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 7:  6128 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 8:  6130 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 9:  6132 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 10:  6134 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 11:  6136 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 12:  6138 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 13:  6140 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 14:  6142 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 15:  6144 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 16:  6146 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 17:  6148 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 18:  6150 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 19:  6152 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 20:  6154 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 21:  6156 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 22:  6158 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 23:  6160 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 24:  6162 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 25:  6164 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 26:  6166 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 27:  6168 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 28:  6170 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 29:  6172 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 30:  6174 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 31:  6176 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 32:  6178 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 33:  6180 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 34:  6182 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 35:  6184 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 36:  6186 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 37:  6188 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 38:  6190 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 39:  6192 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 40:  6194 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 41:  6196 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 42:  6198 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 43:  6200 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 44:  6202 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 45:  6204 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 46:  6206 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 47:  6208 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 48:  6210 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 49:  6212 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 50:  6214 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 51:  6216 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 52:  6218 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 53:  6220 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 54:  6222 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 55:  6224 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 56:  6226 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 57:  6228 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 58:  6230 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 59:  6232 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 60:  6234 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 61:  6236 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 62:  6238 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 63:  6240 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 64:  6242 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 65:  6244 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 66:  6246 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 67:  6248 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 68:  6250 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 69:  6252 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 70:  6254 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 71:  6256 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 72:  6258 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 73:  6260 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 74:  6262 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 75:  6264 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 76:  6266 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 77:  6268 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 78:  6270 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 79:  6272 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 80:  6274 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 81:  6276 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 82:  6278 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 83:  6280 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 84:  6282 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 85:  6284 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 86:  6286 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 87:  6288 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 88:  6290 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 89:  6292 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 90:  6294 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 91:  6296 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 92:  6298 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 93:  6300 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 94:  6302 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 95:  6304 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/gb/30.neglite.program'
./scripts/neg/ijcai19/gb-val/gb-NEGLITE-2-2-b-val.sh: line 96:  6306 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/gb/domain.pddl domains/neg/gb/gb-6-neg-a.pddl $1
