terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 1: 30198 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 2: 30200 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 3: 30202 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 4: 30204 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 5: 30206 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 6: 30208 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 7: 30210 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 8: 30212 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 9: 30214 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 10: 30216 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 11: 30218 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 12: 30220 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 13: 30222 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 14: 30224 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 15: 30226 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 16: 30228 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 17: 30230 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 18: 30232 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 19: 30234 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 20: 30236 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 21: 30238 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 22: 30240 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 23: 30242 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 24: 30244 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 25: 30246 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 26: 30248 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 27: 30250 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 28: 30252 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 29: 30254 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 30: 30256 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 31: 30258 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 32: 30260 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 33: 30262 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 34: 30264 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 35: 30266 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 36: 30268 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 37: 30270 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 38: 30272 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 39: 30274 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 40: 30276 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 41: 30278 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-a-val.sh: line 42: 30280 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
