terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 1: 30283 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 2: 30285 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 3: 30287 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 4: 30289 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 5: 30291 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 6: 30293 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 7: 30295 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 8: 30297 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 9: 30299 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 10: 30301 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 11: 30303 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 12: 30305 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 13: 30307 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 14: 30309 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 15: 30311 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 16: 30313 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 17: 30315 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 18: 30317 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 19: 30319 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 20: 30321 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 21: 30323 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 22: 30325 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 23: 30327 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 24: 30329 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 25: 30331 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 26: 30333 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 27: 30335 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 28: 30337 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 29: 30339 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 30: 30341 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 31: 30343 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 32: 30345 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 33: 30347 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 34: 30349 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 35: 30351 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 36: 30353 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 37: 30355 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 38: 30357 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 39: 30359 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 40: 30361 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 41: 30363 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-1-2-b-val.sh: line 42: 30365 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
