terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 1:  3869 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 2:  3871 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 3:  3873 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 4:  3875 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 5:  3877 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 6:  3879 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 7:  3881 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 8:  3883 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 9:  3885 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 10:  3887 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 11:  3889 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 12:  3891 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 13:  3893 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 14:  3895 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 15:  3897 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 16:  3899 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 17:  3901 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 18:  3903 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 19:  3905 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 20:  3907 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 21:  3909 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 22:  3911 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 23:  3913 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 24:  3915 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 25:  3917 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 26:  3919 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 27:  3921 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 28:  3923 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 29:  3925 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 30:  3927 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 31:  3929 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 32:  3931 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 33:  3933 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 34:  3935 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 35:  3937 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 36:  3939 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 37:  3941 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 38:  3943 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 39:  3945 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 40:  3947 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 41:  3949 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 42:  3951 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 43:  3953 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 44:  3955 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 45:  3957 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 46:  3959 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 47:  3961 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 48:  3963 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 49:  3965 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 50:  3967 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 51:  3969 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 52:  3971 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 53:  3973 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 54:  3975 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 55:  3977 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 56:  3979 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 57:  3981 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 58:  3983 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 59:  3985 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 60:  3987 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 61:  3989 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 62:  3991 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 63:  3993 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 64:  3995 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 65:  3997 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 66:  3999 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 67:  4001 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 68:  4003 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 69:  4005 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 70:  4007 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 71:  4009 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 72:  4011 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 73:  4013 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 74:  4015 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 75:  4017 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 76:  4019 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 77:  4021 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 78:  4023 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 79:  4025 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 80:  4027 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 81:  4029 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 82:  4031 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 83:  4033 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 84:  4035 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 85:  4037 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 86:  4039 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 87:  4041 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 88:  4045 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 89:  4047 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 90:  4049 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 91:  4051 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 92:  4053 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 93:  4055 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 94:  4057 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 95:  4059 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 96:  4061 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 97:  4063 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 98:  4065 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 99:  4067 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/39.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-3-c-val.sh: line 100:  4069 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
