terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 1: 15607 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 2: 15609 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 3: 15611 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 4: 15615 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 5: 15617 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 6: 15619 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 7: 15621 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 8: 15623 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 9: 15625 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 10: 15627 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 11: 15629 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 12: 15631 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 13: 15633 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 14: 15635 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 15: 15637 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 16: 15639 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 17: 15641 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 18: 15643 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 19: 15645 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 20: 15647 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 21: 15649 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 22: 15651 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 23: 15653 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 24: 15655 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 25: 15657 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 26: 15659 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 27: 15661 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 28: 15663 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 29: 15665 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 30: 15667 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 31: 15669 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 32: 15671 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 33: 15673 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 34: 15675 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 35: 15677 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 36: 15679 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 37: 15681 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 38: 15683 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 39: 15685 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 40: 15687 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 41: 15689 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 42: 15691 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 43: 15693 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 44: 15695 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 45: 15697 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 46: 15699 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 47: 15701 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 48: 15703 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 49: 15705 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 50: 15707 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 51: 15709 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 52: 15711 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 53: 15713 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 54: 15715 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 55: 15717 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 56: 15719 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 57: 15721 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 58: 15723 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 59: 15725 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 60: 15727 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 61: 15729 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 62: 15731 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 63: 15733 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 64: 15735 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 65: 15737 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 66: 15739 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 67: 15741 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 68: 15743 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 69: 15745 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 70: 15747 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 71: 15749 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 72: 15751 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 73: 15753 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 74: 15755 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 75: 15757 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 76: 15759 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 77: 15761 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 78: 15763 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 79: 15765 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 80: 15767 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 81: 15769 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 82: 15771 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 83: 15773 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 84: 15775 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 85: 15777 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 86: 15779 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 87: 15781 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 88: 15783 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 89: 15785 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 90: 15787 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 91: 15790 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 92: 15792 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 93: 15794 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 94: 15796 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 95: 15798 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 96: 15800 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 97: 15802 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 98: 15804 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 99: 15806 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 100: 15808 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 101: 15810 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/27.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-2-1-c-val.sh: line 102: 15812 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-b.pddl $1
